services:
  app:
    container_name: inethi-monitoring-dev
    restart: no
    env_file:
      - ./.env
    build:
      context: .
      args:
        - DEV=${DEV:-true}
    ports:
      - "8100:8000"
    volumes:
      - ./monitoring:/monitoring
    entrypoint: ["/monitoring/run.sh"]
    environment:
      - DB_HOST=${DB_HOST:-db}
      - DB_NAME=${DB_NAME:-devdb}
      - DB_USER=${DB_USER:-devuser}
      - DB_PASS=${DB_PASS:-devpass}
    depends_on:
      - db

  db:
    image: timescale/timescaledb:latest-pg17
    container_name: inethi-monitoring-db-timescale-dev
    restart: no
    env_file:
      - ./.env
    volumes:
      - dev-db-data-monitoring-timescale:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME:-devdb}
      - POSTGRES_USER=${DB_USER:-devuser}
      - POSTGRES_PASSWORD=${DB_PASS:-devpass}

  redis:
    image: redis:alpine
    container_name: inethi-monitoring-celery-redis-dev
    restart: no
  celery:
    container_name: inethi-monitoring-celery-dev
    build:
      context: .
    env_file:
      - ./.env

    command: celery -A monitoring worker -l INFO
    volumes:
      - ./monitoring:/monitoring
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    restart: no
    depends_on:
      - redis
      - db

  celery_beat:
    container_name: inethi-monitoring-celery-beat-dev
    build:
      context: .
    env_file:
      - ./.env
    command: celery -A monitoring beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - ./monitoring:/monitoring
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    restart: no
    depends_on:
      - redis
      - db

volumes:
  dev-db-data-monitoring-timescale:
