# Generated by Django 5.1.7 on 2025-03-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_ping'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='cloud_pk',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
