# Generated by Django 5.1.7 on 2025-03-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_network_cloud_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='cloud_pk',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
