# Generated by Django 5.1.7 on 2025-07-16 10:01

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_host_cloud_pk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid MAC address in format XX:XX:XX:XX:XX:XX.', regex='^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$')]),
        ),
        migrations.AddConstraint(
            model_name='host',
            constraint=models.UniqueConstraint(condition=models.Q(('mac_address__isnull', False)), fields=('mac_address',), name='unique_mac_address_not_null'),
        ),
    ]
